name: hello-world
on: push
jobs:
   my-job:
    name:  Test-job
    runs-on:
      - sekhar-test
    steps:
      - name: my-step
        run: echo "Hello World!"
      - name: step-2
        run: |
          echo "Welcome to the Github actions"
          sleep 15
          echo "curent date is $(date)"
          echo "Good Byee,have a good sleep"
   my-job2:
    name: Test-job-2
    runs-on:
      - sekhar-test
    steps:
      - name: checkout the Terrafrom version
        uses: hashicorp/setup-terraform@v2.0.2

      - name: Terraform-init
        run: |
          terraform init
          $(pwd)
          echo "this is the current terraform_version: $(terraform --version)"
      