name: first_actions
on:
  push:
    branches:
      - "main"
      - "dev_branch"
env:
 var1: "TODAY_DATA_IS:"
jobs:
  sample_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: chekout repository code
        uses: actions/checkout@v3
      - name: print sample message
        run: |
          echo "${var1} $(date)"
  sample_second_job:
    runs-on: ubuntu-latest
    steps:
      - name: print sample message
        run: |
          echo "this is secons JOb"
