name: first_actions
on:
  push:
    branches:
      - "main"
      - "dev_branch"
env:
 var1: "TODAY_DATA_IS:"
 var2: "THE CURRUNT TERRAFORM VERSION IS...."
jobs:
  checkout_and_insatll:
    runs-on: ubuntu-latest
    steps:
      - name: chekout repository code
        uses: actions/checkout@v3
      - name: install terrafrom
        uses: hashicorp/setup-terraform@v1
      - name: Initialize Terrafrom
        run: terraform init
      - name: Terrafrom formate resources
        run: terrafrom fmt
      
