name: first_actions
on:
  push:
    branches:
      - "main"
      - "dev_branch"
env:
 var1: "TODAY_DATA_IS:"
 var2: "THE CURRUNT TERRAFORM VERSION IS...."
jobs:
  checkout_and_insatll:
    runs-on: ubuntu-latest
    steps:
      - name: chekout repository code
        uses: actions/checkout@v3
      - name: install terrafrom
        uses: hashicorp/setup-terraform@v1
      - name: config aws creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: $acces_key
          aws-secret-access-key: $secrect_key
          aws-region: "us-east-1"
        env:
         acces_key: ${{secrets.AWS_KEY}}
         secret_key:  ${{secrets.SECRET_KEY}} 
      - name: check the AWS identity
        run: aws sts get-caller-identity       
      # - name: Initialize Terrafrom
      #   run: terraform init
      # - name: Terrafrom formate resources
      #   run: terraform fmt
      # - name: terrafrom planned resources
      #   run: terraform plan
      
