name: first_actions
on:
  push:
    branches:
      - "main"
      - "dev_branch"
env:
 var1: "TODAY_DATA_IS:"
 var2: "THE CURRUNT TERRAFORM VERSION IS...."
jobs:
  checkout_and_insatll:
    runs-on: ubuntu-latest
    steps:
      - name: chekout repository code
        uses: actions/checkout@v3
      - name: install terrafrom
        uses: hashicorp/setup-terraform@v1
      - name: config aws creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_KEY}}
          aws-secret-access-key: ${{secrets.SECRET_KEY}} 
          aws-region: "us-east-1"
      
      - name: check the AWS identity
        run: aws sts get-caller-identity       
      - name: Initialize Terrafrom
        run: terraform init
      - name: Terrafrom formate resources
        run: terraform fmt
      - name:  terraform apply
        run: |
          if [ ${{ github.ref }} == 'refs/heads/main' ];then
            terraform plan
            terraform apply --auto-approve
          elif [ ${{ github.ref }} == 'refs/heads/dev_branch' ];then
            echo "this is ...............${{ github.ref }}"
            echo "+++++++++++++++++++++++"
            terraform plan
          fi
              
