name: first_actions
on:
  push:
    branches:
      - "main"
      - "dev_branch"
env:
 var1: "TODAY_DATA_IS:"
 var2: "THE CURRUNT TERRAFORM VERSION IS...."
jobs:
  sample_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: chekout repository code
        uses: actions/checkout@v3
      - name: install terrafrom
        uses: hashicorp/setup-terraform@v1
      - name: check the Terrafrom version
        run: |
          terraform --version
          echo "this is secons JOb"
          echo "$(var2) $(terrafrom --version)"

